### PR TITLE
Delete cached files from old version

### LINKED ISSUE #113: Conference selection is "broken" after updating from previous version
When I select Devoxx Belgium from the new home page on an Android device, the actual event is not selected.  As a result no speakers are shown and the actual event title shows only "Devoxx" instead of "Devoxx BE" !! 

This is not the case in the iOS version.

image

### PR DESCRIPTION
**Pull request by abhinayagarwal**
Deletes all cached files from previous version of the app

Fixes #113

### CODE REVIEW

File: DevoxxClientCommon/src/main/java/com/devoxx/util/DevoxxSettings.java [hunk 1]
```diff
@@ -117,6 +117,7 @@
     public static final String BADGE_SPONSOR = "badge-sponsor";
     public static final String RELOAD = "reload";
     public static final String RATING = "rating";
+    public static final String NEW_VERSION = "newVersion";
```
Comment (tiainen) [inline DevoxxClientCommon/src/main/java/com/devoxx/util/DevoxxSettings.java]: It is probably best to give this a more explicit name like "version_3_0_0"?

Comment (abhinayagarwal) [reply DevoxxClientCommon/src/main/java/com/devoxx/util/DevoxxSettings.java]: Good idea. Makes it easy to trace back.
